[metadata]
name = xense_ros2
version = 0.1.0
description = ROS2 package to publish sensor data from xensesdk (single-device)

[options]
packages = find:
install_requires =
    rclpy
    numpy
    cv_bridge

[options.entry_points]
console_scripts =
    xense_publisher_ros2 = xense_ros2.xense_publisher_ros2:main
